// <auto-generated />
namespace LearningDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addanassocationbetweenthetaskandtheuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addanassocationbetweenthetaskandtheuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201809022213363_Add an assocation between the task and the user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
