// <auto-generated />
namespace LearningDotNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemovedForeignKeyrelationshipandjustaddedanIdPropertyforStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedForeignKeyrelationshipandjustaddedanIdPropertyforStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201809020104475_Removed Foreign Key relationship and just added an Id Property for Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
